# Generated by Django 3.0.2 on 2021-02-18 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_productcategory_monthly_capacity'),
        ('purchase', '0004_auto_20210218_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='desired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='ordered_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='stock.Product'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
    ]
