# Generated by Django 3.0.2 on 2021-02-18 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_productcategory_monthly_capacity'),
        ('purchase', '0005_auto_20210218_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('ordered_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('status', models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Pending Quality Control', 'Pending Quality Control'), ('Rejected', 'Rejected'), ('Product To Be Destroyed', 'Product To Be Destroyed'), ('Supplier Return', 'Supplier Return')], default='Accepted', max_length=32, null=True)),
                ('reception_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.Order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orderdetail_set', to='stock.Product'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orderdetail_set', to='stock.Warehouse'),
        ),
        migrations.RenameModel(
            old_name='Reception',
            new_name='Receipt',
        ),
        migrations.DeleteModel(
            name='ReceptionDetail',
        ),
        migrations.AddField(
            model_name='receiptiondetail',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.Receipt'),
        ),
        migrations.AddField(
            model_name='receiptiondetail',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.Warehouse'),
        ),
    ]
