# Generated by Django 3.0.2 on 2021-02-18 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_productcategory_monthly_capacity'),
        ('purchase', '0006_auto_20210218_1119'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReceiptionDetail',
            new_name='ReceiptDetail',
        ),
    ]
