# Generated by Django 3.0.2 on 2021-02-18 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_auto_20210218_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='delivered_at',
            new_name='receipt_at',
        ),
        migrations.RenameField(
            model_name='receiptdetail',
            old_name='reception_at',
            new_name='receipt_at',
        ),
        migrations.AddField(
            model_name='receiptdetail',
            name='order_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.OrderDetail'),
        ),
        migrations.AlterField(
            model_name='receiptdetail',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Accepted'), ('Q', 'Pending Quality Control'), ('R', 'Rejected'), ('PD', 'Product To Be Destroyed'), ('SR', 'Supplier Return')], default='A', max_length=32, null=True),
        ),
    ]
