# Generated by Django 3.0.2 on 2021-02-19 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_auto_20210218_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiptdetail',
            old_name='ordered_quantity',
            new_name='receipted_quantity',
        ),
    ]
