# Generated by Django 3.0.2 on 2021-02-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_auto_20210219_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='ordered_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
