# Generated by Django 3.0.2 on 2021-02-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_auto_20210219_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptdetail',
            name='receipted_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
