# Generated by Django 3.0.2 on 2021-02-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0011_auto_20210219_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptdetail',
            name='receipt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
