# Generated by Django 3.0.2 on 2021-03-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0012_auto_20210223_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='incoterm',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('Import', 'Import'), ('Local', 'Local')], default='Local', max_length=32, null=True),
        ),
    ]
