# Generated by Django 3.0.2 on 2021-03-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0013_auto_20210301_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptdetail',
            name='expedit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
