# Generated by Django 3.0.2 on 2021-02-17 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_productcategory_monthly_capacity'),
        ('inventory', '0002_auto_20210122_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.Warehouse'),
        ),
    ]
